name: Run KiBot Checks

on:
  push:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '.github/workflows/kibot_checks.yml'
    branches-ignore:
      - gh-pages
  pull_request:
    paths:
      - '**.kicad_sch'
      - '**.kicad_pcb'
      - '.github/workflows/kibot_checks.yml'
    branches-ignore:
      - gh-pages

jobs:
  kibot-check:
    runs-on: ubuntu-latest

    steps:
    - name: Get repo
      uses: actions/checkout@v3
      with:
        submodules: "recursive"

    - name: Run KiBot
      uses: INTI-CMNB/KiBot@v2_k8_1_6_5
      with:
        config: kicad/checks.kibot.yaml
        # optional - prefix to output defined in config
        dir: output
        # optional - schematic file
        schema: 'kicad/bms-c1.kicad_sch'
        # optional - PCB design file
        board: 'kicad/bms-c1.kicad_pcb'
